<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EasyAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DressSharp/DressSharp.csproj" />
    <ProjectReference Include="../DressSharp.TestSupport/DressSharp.TestSupport.csproj" />
  </ItemGroup>
</Project>
