using Microsoft.Extensions.FileSystemGlobbing;

namespace DressSharp.CommandLine;

sealed class FileSelector(string invocationDirectory, GitFileDiscovery? git = null)
{
    static readonly HashSet<string> VcsDirectories = new(StringComparer.OrdinalIgnoreCase) { ".git", ".hg", ".svn" };
    static readonly string[] GeneratedSuffixes = [".g.cs", ".generated.cs", ".designer.cs"];
    readonly string _invocationDirectory = Path.GetFullPath(invocationDirectory);
    readonly GitFileDiscovery _git = git ?? new();

    internal async Task<IReadOnlyList<SelectedFile>> Select(IReadOnlyList<string> includes, CancellationToken cancellationToken = default)
    {
        var matcher = CreateMatcher(includes);
        var discovered = await _git.TryListAsync(_invocationDirectory, cancellationToken)
            ?? EnumerateFiles();
        var candidates = discovered
            .Where(IsCSharp)
            .Where(path => !IsVcsPath(path))
            .Where(path => File.Exists(Path.GetFullPath(path, _invocationDirectory)))
            .Distinct(PathIdentityComparer())
            .ToArray();
        var selected = matcher.Match(candidates).Files
            .Select(match => match.Path.Replace('\\', '/'))
            .Distinct(PathIdentityComparer())
            .Select(path => new SelectedFile(Path.GetFullPath(path, _invocationDirectory), path))
            .OrderBy(file => file.DisplayPath, StringComparer.Ordinal)
            .ToArray();

        var generated = new bool[selected.Length];
        await Parallel.ForAsync(
            0,
            selected.Length,
            new ParallelOptions
                {
                    CancellationToken = cancellationToken,
                    MaxDegreeOfParallelism = Environment.ProcessorCount
                },
            async (index, token) => generated[index] = await IsGeneratedAsync(selected[index].FullPath, token));

        return selected.Where((_, index) => !generated[index]).ToArray();
    }

    static Matcher CreateMatcher(IReadOnlyList<string> includes)
    {
        var matcher = new Matcher(PathComparison());
        try
        {
            foreach (var include in includes.Count == 0 ? ["**/*.cs"] : includes)
                matcher.AddInclude(Normalize(include));
        }
        catch (ArgumentException exception)
        {
            throw new FileSelectionException($"Invalid include glob: {exception.Message}");
        }
        return matcher;
    }

    string[] EnumerateFiles()
    {
        try
        {
            var options = new EnumerationOptions
                {
                    AttributesToSkip = FileAttributes.ReparsePoint,
                    IgnoreInaccessible = false,
                    MatchCasing = MatchCasing.CaseInsensitive,
                    RecurseSubdirectories = true,
                    ReturnSpecialDirectories = false,
                };
            return Directory.EnumerateFiles(_invocationDirectory, "*.cs", options)
                .Select(path => Path.GetRelativePath(_invocationDirectory, path).Replace('\\', '/'))
                .ToArray();
        }
        catch (Exception exception) when (exception is UnauthorizedAccessException or IOException)
        {
            throw new FileSelectionException($"Path is inaccessible: {_invocationDirectory}");
        }
    }

    static string Normalize(string include)
    {
        if (string.IsNullOrWhiteSpace(include))
            throw new FileSelectionException("Include cannot be empty.");
        if (include == "-")
            throw new FileSelectionException("Standard input is not supported.");
        if (Path.IsPathRooted(include))
            throw new FileSelectionException($"Include globs must be relative to the invocation directory: {include}");

        var pattern = include.Replace('\\', '/');
        if (pattern.Split('/').Contains("..", StringComparer.Ordinal))
            throw new FileSelectionException($"Include globs cannot leave the invocation directory: {include}");
        return pattern.StartsWith("./", StringComparison.Ordinal) ? pattern[2..] : pattern;
    }

    static bool IsCSharp(string path) => path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase);

    static bool IsVcsPath(string path) => path.Split('/').Any(VcsDirectories.Contains);

    static async Task<bool> IsGeneratedAsync(string path, CancellationToken cancellationToken)
    {
        if (GeneratedSuffixes.Any(suffix => path.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)))
            return true;

        using var reader = new StreamReader(path, detectEncodingFromByteOrderMarks: true);
        for (var count = 0; count < 20 && await reader.ReadLineAsync(cancellationToken) is { } line; count++)
        {
            var trimmed = line.TrimStart();
            if (trimmed.Length != 0)
            {
                return trimmed.StartsWith("//", StringComparison.Ordinal)
                    && trimmed.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase);
            }
        }
        return false;
    }

    static StringComparer PathIdentityComparer() => StringComparer.FromComparison(PathComparison());

    static StringComparison PathComparison() => OperatingSystem.IsWindows()
        ? StringComparison.OrdinalIgnoreCase
        : StringComparison.Ordinal;
}
