<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DressSharp.Docs</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Markdig" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DressSharp/DressSharp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="site.css" LogicalName="site.css" />
  </ItemGroup>
</Project>
