using System.Reflection;
using DressSharp.Docs;

var output = Path.GetFullPath("artifacts/site");
string? repository = null;
for (var i = 0; i < args.Length; i++)
{
    switch (args[i])
    {
        case "--output" when i + 1 < args.Length:
            output = Path.GetFullPath(args[++i]);
            break;
        case "--repository" when i + 1 < args.Length:
            repository = args[++i];
            break;
        default:
            Console.Error.WriteLine("Usage: DressSharp.Docs [--output <directory>] [--repository <url>]");
            return 2;
    }
}

// GitHub Actions names the repository in the environment, so the workflow need not forward arguments.
repository ??= Environment.GetEnvironmentVariable("GITHUB_REPOSITORY") is { Length: > 0 } slug
    ? $"https://github.com/{slug}"
    : null;

var version = typeof(DressSharp.Program).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion
    ?? typeof(DressSharp.Program).Assembly.GetName().Version?.ToString()
    ?? "0.0.0";
version = version.Split('+')[0];

using var cancellation = new CancellationTokenSource();
Console.CancelKeyPress += (_, e) =>
    {
        e.Cancel = true;
        cancellation.Cancel();
    };

var groups = await CatalogReader.ReadAsync(cancellation.Token);
// Only a directory this generator produced, or an empty one, is replaced; anything else is refused
// rather than deleted.
if (Directory.Exists(output))
{
    var entries = Directory.EnumerateFileSystemEntries(output).Any();
    if (entries && !File.Exists(Path.Combine(output, ".nojekyll")))
    {
        Console.Error.WriteLine($"{output} exists and was not generated by DressSharp.Docs; choose an empty --output.");
        return 2;
    }
    Directory.Delete(output, recursive: true);
}
await new SiteWriter(output, repository, version).WriteAsync(groups, cancellation.Token);

var rules = groups.Sum(group => group.Rules.Count());
var outcomes = groups.Sum(group => group.Rules.Sum(rule => rule.Outcomes.Length));
Console.WriteLine($"Wrote {rules} rules with {outcomes} formatted examples to {output}");
return 0;
