using DressSharp.CommandLine;
using Xunit;

namespace DressSharp.UnitTests;

public sealed class FileSelectorTests : IDisposable
{
    readonly string directory = Directory.CreateDirectory(
        Path.Combine(Path.GetTempPath(), "DressSharp.UnitTests", Guid.NewGuid().ToString("N"))).FullName;

    [Fact]
    public async Task Empty_includes_recursively_select_eligible_files_in_display_order()
    {
        Write("z.cs", "class Z {}");
        Write("a.cs", "class A {}");
        Write("notes.txt", "no");
        Write("obj/code.g.cs", "class Generated {}");
        Write("header.cs", "// <auto-generated />\nclass Generated {}");
        Write(".git/hidden.cs", "class Hidden {}");

        var selected = await Select();

        Assert.Equal(["a.cs", "z.cs"], selected.Select(file => file.DisplayPath));
    }

    [Fact]
    public async Task Explicit_generated_file_is_excluded_but_unsupported_file_fails()
    {
        Write("code.designer.cs", "class Generated {}");
        Write("notes.txt", "no");

        Assert.Empty(await Select("code.designer.cs"));
        var exception = await Assert.ThrowsAsync<FileSelectionException>(() => Select("notes.txt"));
        Assert.Contains("Unsupported file path", exception.Message);
    }

    [Fact]
    public async Task Overlapping_includes_are_canonicalized()
    {
        Write("src/code.cs", "class C {}");

        var selected = await Select("src", "src/code.cs", ".");

        Assert.Single(selected);
        Assert.Equal("src/code.cs", selected[0].DisplayPath);
    }

    [Fact]
    public async Task Glob_includes_are_relative_and_composable()
    {
        Write("root.cs", "class Root {}");
        Write("src/direct.cs", "class Direct {}");
        Write("src/nested/deep.cs", "class Deep {}");
        Write("tests/test.cs", "class Test {}");

        var selected = await Select("*.cs", "src/**/*.cs");

        Assert.Equal(["root.cs", "src/direct.cs", "src/nested/deep.cs"], selected.Select(file => file.DisplayPath));
    }

    [Fact]
    public async Task Glob_includes_retain_ignore_and_generated_file_filters()
    {
        Write(".gitignore", "src/ignored.cs\n");
        Write("src/included.cs", "class Included {}");
        Write("src/ignored.cs", "class Ignored {}");
        Write("src/generated.g.cs", "class Generated {}");
        Write("src/header.cs", "// <auto-generated />\nclass Generated {}");

        var selected = await Select("src/**/*.cs");

        Assert.Equal(["src/included.cs"], selected.Select(file => file.DisplayPath));
    }

    [Fact]
    public async Task Glob_without_matches_selects_nothing()
    {
        Write("source.cs", "class Source {}");

        Assert.Empty(await Select("tests/**/*.cs"));
    }

    [Fact]
    public async Task Nested_gitignore_rules_and_negation_are_honored()
    {
        Write(".gitignore", "ignored/\n*.skip.cs\n!keep.skip.cs\n");
        Write("ignored/no.cs", "class No {}");
        Write("drop.skip.cs", "class Drop {}");
        Write("keep.skip.cs", "class Keep {}");
        Write("nested/.gitignore", "*.cs\n!yes.cs\n");
        Write("nested/no.cs", "class No {}");
        Write("nested/yes.cs", "class Yes {}");

        var selected = await Select();

        Assert.Equal(["keep.skip.cs", "nested/yes.cs"], selected.Select(file => file.DisplayPath));
    }

    [Fact]
    public async Task Gitignore_character_ranges_double_stars_and_escapes_are_honored()
    {
        Write(".gitignore", "logs/**/trace[0-9].cs\n\\#generated.cs\nspace\\ .cs\n");
        Write("logs/trace1.cs", "class Ignored {}");
        Write("logs/deep/trace2.cs", "class Ignored {}");
        Write("logs/deep/traceX.cs", "class Included {}");
        Write("#generated.cs", "class Ignored {}");
        Write("space .cs", "class Ignored {}");

        var selected = await Select();

        Assert.Equal(["logs/deep/traceX.cs"], selected.Select(file => file.DisplayPath));
    }

    [Fact]
    public async Task Negation_cannot_reinclude_a_file_below_an_ignored_directory()
    {
        Write(".gitignore", "ignored/\n!ignored/keep.cs\n");
        Write("ignored/keep.cs", "class Ignored {}");

        Assert.Empty(await Select());
    }

    [Theory]
    [InlineData("-")]
    [InlineData("missing.cs")]
    [InlineData("../**/*.cs")]
    public async Task Invalid_includes_fail_preflight(string include)
    {
        await Assert.ThrowsAsync<FileSelectionException>(() => Select(include));
    }

    Task<IReadOnlyList<SelectedFile>> Select(params string[] includes) =>
        new FileSelector(directory).SelectAsync(includes, TestContext.Current.CancellationToken);

    void Write(string relativePath, string text)
    {
        var path = Path.Combine(directory, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, text);
    }

    public void Dispose()
    {
        Directory.Delete(directory, true);
        GC.SuppressFinalize(this);
    }
}
