using System.Diagnostics;
using DressSharp.CommandLine;
using Xunit;
using EasyAssertions;

namespace DressSharp.UnitTests;

public sealed class FileSelectorTests : IDisposable
{
    readonly string _directory = Directory.CreateDirectory(
        Path.Combine(Path.GetTempPath(), "DressSharp.UnitTests", Guid.NewGuid().ToString("N"))).FullName;

    public FileSelectorTests() => RunGit(_directory, "init", "--quiet");

    [Fact]
    public async Task Empty_includes_recursively_select_eligible_files_in_display_order()
    {
        Write("z.cs", "class Z {}");
        Write("a.cs", "class A {}");
        Write("notes.txt", "no");
        Write("obj/code.g.cs", "class Generated {}");
        Write("header.cs", "// <auto-generated />\nclass Generated {}");
        Write(".git/hidden.cs", "class Hidden {}");

        var selected = await Select();

        selected.Select(file => file.DisplayPath).ShouldMatch(["a.cs", "z.cs"]);
    }

    [Fact]
    public async Task Exact_patterns_still_filter_non_csharp_and_generated_files()
    {
        Write("code.designer.cs", "class Generated {}");
        Write("notes.txt", "no");

        (await Select("code.designer.cs")).ShouldBeEmpty();
        (await Select("notes.txt")).ShouldBeEmpty();
        (await Select("missing.cs")).ShouldBeEmpty();
    }

    [Fact]
    public async Task Overlapping_includes_are_canonicalized()
    {
        Write("src/code.cs", "class C {}");

        (await Select("src/**/*.cs", "src/code.cs", "**/*.cs"))
            .ShouldBeASingular<SelectedFile>()
            .And.DisplayPath.ShouldBe("src/code.cs");
    }

    [Fact]
    public async Task Glob_includes_are_relative_and_composable()
    {
        Write("root.cs", "class Root {}");
        Write("src/direct.cs", "class Direct {}");
        Write("src/nested/deep.cs", "class Deep {}");
        Write("tests/test.cs", "class Test {}");

        var selected = await Select("*.cs", "src/**/*.cs");

        selected.Select(file => file.DisplayPath)
            .ShouldMatch(["root.cs", "src/direct.cs", "src/nested/deep.cs"]);
    }

    [Fact]
    public async Task Glob_includes_retain_ignore_and_generated_file_filters()
    {
        Write(".gitignore", "src/ignored.cs\n");
        Write("src/included.cs", "class Included {}");
        Write("src/ignored.cs", "class Ignored {}");
        Write("src/generated.g.cs", "class Generated {}");
        Write("src/header.cs", "// <auto-generated />\nclass Generated {}");

        var selected = await Select("src/**/*.cs");

        selected.Select(file => file.DisplayPath)
            .ShouldMatch(["src/included.cs"]);
    }

    [Fact]
    public async Task Glob_without_matches_selects_nothing()
    {
        Write("source.cs", "class Source {}");

        (await Select("tests/**/*.cs")).ShouldBeEmpty();
    }

    [Fact]
    public async Task Filesystem_globbing_is_used_outside_a_git_worktree()
    {
        var root = Directory.CreateDirectory(
            Path.Combine(Path.GetTempPath(), "DressSharp.UnitTests.Fallback", Guid.NewGuid().ToString("N"))).FullName;
        try
        {
            Write(root, "root.cs", "class Root {}");
            Write(root, "src/nested.cs", "class Nested {}");
            Write(root, "src/generated.g.cs", "class Generated {}");

            var selected = await new FileSelector(root).Select(["src/**/*.cs"], TestContext.Current.CancellationToken);

            selected.Select(file => file.DisplayPath)
                .ShouldMatch(["src/nested.cs"]);
        }
        finally
        {
            Directory.Delete(root, true);
        }
    }

    [Fact]
    public async Task Nested_gitignore_rules_and_negation_are_honored()
    {
        Write(".gitignore", "ignored/\n*.skip.cs\n!keep.skip.cs\n");
        Write("ignored/no.cs", "class No {}");
        Write("drop.skip.cs", "class Drop {}");
        Write("keep.skip.cs", "class Keep {}");
        Write("nested/.gitignore", "*.cs\n!yes.cs\n");
        Write("nested/no.cs", "class No {}");
        Write("nested/yes.cs", "class Yes {}");

        var selected = await Select();

        selected.Select(file => file.DisplayPath).ShouldMatch(["keep.skip.cs", "nested/yes.cs"]);
    }

    [Fact]
    public async Task Tracked_files_remain_eligible_when_ignored()
    {
        Write("tracked.cs", "class Tracked {}");
        RunGit(_directory, "add", "--", "tracked.cs");
        Write(".gitignore", "*.cs\n");
        Write("untracked.cs", "class Untracked {}");

        var selected = await Select();

        selected.Select(file => file.DisplayPath).ShouldMatch(["tracked.cs"]);
    }

    [Fact]
    public async Task Gitignore_character_ranges_double_stars_and_escapes_are_honored()
    {
        Write(".gitignore", "logs/**/trace[0-9].cs\n\\#generated.cs\nspace\\ .cs\n");
        Write("logs/trace1.cs", "class Ignored {}");
        Write("logs/deep/trace2.cs", "class Ignored {}");
        Write("logs/deep/traceX.cs", "class Included {}");
        Write("#generated.cs", "class Ignored {}");
        Write("space .cs", "class Ignored {}");

        var selected = await Select();

        selected.Select(file => file.DisplayPath).ShouldMatch(["logs/deep/traceX.cs"]);
    }

    [Fact]
    public async Task Negation_cannot_reinclude_a_file_below_an_ignored_directory()
    {
        Write(".gitignore", "ignored/\n!ignored/keep.cs\n");
        Write("ignored/keep.cs", "class Ignored {}");

        (await Select()).ShouldBeEmpty();
    }

    [Fact]
    public async Task Staged_scope_selects_only_files_whose_index_differs_from_head()
    {
        Write("committed.cs", "class Committed {}");
        Write("staged.cs", "class Staged {}");
        Write("removed.cs", "class Removed {}");
        Commit("committed.cs", "staged.cs", "removed.cs");
        Write("staged.cs", "class Staged { }");
        Write("unstaged.cs", "class Unstaged {}");
        RunGit(_directory, "add", "--", "staged.cs");
        RunGit(_directory, "rm", "--quiet", "--", "removed.cs");

        var selected = await Select(SelectionScope.Staged);

        selected.Select(file => file.DisplayPath).ShouldMatch(["staged.cs"]);
    }

    [Fact]
    public async Task Changed_scope_selects_modified_and_untracked_files_and_honours_includes()
    {
        Write("committed.cs", "class Committed {}");
        Write("modified.cs", "class Modified {}");
        Commit("committed.cs", "modified.cs");
        Write("modified.cs", "class Modified { }");
        Write("src/untracked.cs", "class Untracked {}");
        Write(".gitignore", "ignored.cs\n");
        Write("ignored.cs", "class Ignored {}");

        (await Select(SelectionScope.Changed)).Select(file => file.DisplayPath)
            .ShouldMatch(["modified.cs", "src/untracked.cs"]);
        (await Select(SelectionScope.Changed, "src/**/*.cs")).Select(file => file.DisplayPath)
            .ShouldMatch(["src/untracked.cs"]);
    }

    [Fact]
    public async Task Changed_scope_treats_every_file_as_new_before_the_first_commit()
    {
        Write("tracked.cs", "class Tracked {}");
        RunGit(_directory, "add", "--", "tracked.cs");
        Write("untracked.cs", "class Untracked {}");

        var selected = await Select(SelectionScope.Changed);

        selected.Select(file => file.DisplayPath).ShouldMatch(["tracked.cs", "untracked.cs"]);
    }

    [Fact]
    public async Task Scoped_selection_requires_a_git_worktree()
    {
        var root = Directory.CreateDirectory(
            Path.Combine(Path.GetTempPath(), "DressSharp.UnitTests.Fallback", Guid.NewGuid().ToString("N"))).FullName;
        try
        {
            var exception = await Assert.ThrowsAsync<FileSelectionException>(
                () => new FileSelector(root).Select([], SelectionScope.Staged, TestContext.Current.CancellationToken));
            exception.Message.ShouldContain("--staged");
        }
        finally
        {
            Directory.Delete(root, true);
        }
    }

    [Theory]
    [InlineData("")]
    [InlineData("-")]
    [InlineData("../**/*.cs")]
    public async Task Invalid_includes_fail_preflight(string include)
    {
        Select(include).ShouldFailWith<FileSelectionException>();
    }

    [Fact]
    public async Task Rooted_include_fails_preflight()
    {
        var include = Path.Combine(_directory, "**", "*.cs");

        Select(include).ShouldFailWith<FileSelectionException>();
    }

    Task<IReadOnlyList<SelectedFile>> Select(params string[] includes) =>
        new FileSelector(_directory).Select(includes, TestContext.Current.CancellationToken);

    Task<IReadOnlyList<SelectedFile>> Select(SelectionScope scope, params string[] includes) =>
        new FileSelector(_directory).Select(includes, scope, TestContext.Current.CancellationToken);

    void Commit(params string[] files)
    {
        RunGit(_directory, ["add", "--", .. files]);
        RunGit(_directory, "-c", "user.name=DressSharp", "-c", "user.email=tests@dresssharp.invalid", "commit", "--quiet", "--no-gpg-sign", "-m", "commit");
    }

    void Write(string relativePath, string text) =>
        Write(_directory, relativePath, text);

    static void Write(string root, string relativePath, string text)
    {
        var path = Path.Combine(root, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, text);
    }

    static void RunGit(string directory, params string[] arguments)
    {
        var startInfo = new ProcessStartInfo("git")
            {
                CreateNoWindow = true,
                RedirectStandardError = true,
                UseShellExecute = false,
            };
        startInfo.ArgumentList.Add("-C");
        startInfo.ArgumentList.Add(directory);
        foreach (var argument in arguments)
            startInfo.ArgumentList.Add(argument);
        using var process = Process.Start(startInfo)!;
        var error = process.StandardError.ReadToEnd();
        process.WaitForExit();
        (process.ExitCode == 0).ShouldBe(true, error);
    }

    public void Dispose()
    {
        foreach (var file in Directory.EnumerateFiles(_directory, "*", SearchOption.AllDirectories))
            File.SetAttributes(file, FileAttributes.Normal);
        Directory.Delete(_directory, true);
    }
}
